### ISSUE TITLE
Svelte Router

### ISSUE THREAD

**Issue by Shyam-Chen** [Shyam-Chen/Svelte-Starter#10]
### Features:

* [ ] Lazy Loading
* [ ] Dynamic Route Matching
* [ ] Nested Routes
* [ ] Guards
* [ ] Meta Data
* [ ] Transitions
* [ ] Modular

**Comment by timeshift92** [comment]
i recomended https://github.com/qutran/swheel

**Comment by Shyam-Chen** [comment]
I used `svelte-navigator`.
